//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by foo_logitech_lcd.rc
//
#define IDD_CONFIG_MAIN                 101
#define IDD_LCD_CFG_TAB                 104
#define IDD_VIS_CFG_TAB                 105
#define IDD_SPEC_CFG                    106
#define IDD_OSC_CFG                     111
#define IDD_VU_CFG                      112
#define IDD_BLOCK_SPEC_CFG              113
#define IDD_VU_PIC_CFG                  114
#define IDD_TRACK_INFO_TAB_1_EXPERT     116
#define IDD_TRACK_INFO_TAB_2            117
#define IDD_TRACK_INFO_TAB_1            118
#define IDD_TRACK_INFO_TABS_CFG         120
#define IDC_LINE1_EDIT                  1001
#define IDC_LINE2_EDIT                  1002
#define IDC_LINE3_EDIT                  1003
#define IDC_LINE4_EDIT                  1004
#define IDC_LINE4_RADIO                 1005
#define IDC_PROGRESS_RADIO              1006
#define IDC_VSYNC_CHECK                 1007
#define IDC_EXPERT_CHECK                1008
#define IDC_START_WITH_CHECK            1009
#define IDC_PROGRESS_CHECK              1010
#define IDC_ENABLED_CHECK               1011
#define IDC_PRIORITY_CHECK              1012
#define IDC_TRACK_INFO_CHECK            1013
#define IDC_FORCE_FG_CHECK              1014
#define IDC_RANDOM_VIS_CHECK            1015
#define IDC_BG_PAUSE_CHECK              1016
#define IDC_REMEBER_RADIO               1017
#define IDC_START_RADIO                 1018
#define IDC_PERM_PROGRESS_CHECK         1019
#define IDC_OVERLAP_CHECK               1024
#define IDC_FONT_ALIGN_V_COMBO          1028
#define IDC_SCROLL_MODE_V_COMBO         1029
#define IDC_COLOUR_2_BUTTON             1034
#define IDC_FONT_BUTTON                 1036
#define IDC_CONFIG_TABS                 1046
#define IDC_STATIC_SIZER                1049
#define IDC_RAND_TIME_EDIT              1051
#define IDC_TRACK_INFO_EDIT             1052
#define IDC_RAND_TIME_STATIC            1053
#define IDC_TRACK_INFO_TIME_STATIC      1054
#define IDC_BG_NONE_RADIO               1055
#define IDC_BG_ART_RADIO                1056
#define IDC_BG_FILE_RADIO               1057
#define IDC_BG_FILE_EDIT                1058
#define IDC_SLIT_SCREEN_CHECK           1059
#define IDC_VIS_TREE                    1060
#define IDC_VIS_CFG_SIZER_STATIC        1061
#define IDC_BG_PIC_STRETCH_CHECK        1063
#define IDC_BG_MODE_CHECK               1064
#define IDC_ALLOW_HW_CHECK              1065
#define IDC_TRAIL_EFFECT_CHECK          1066
#define IDC_COLOUR_2_STATIC_TEXT        1067
#define IDC_BG_PIC_STRETCH_CHECK2       1067
#define IDC_BG_PIC_CLEAR_TEXT_CHECK     1067
#define IDC_COLOUR_2_STATIC             1068
#define IDC_BG_COLOUR_STATIC            1069
#define IDC_BG_COLOUR_STATIC_TEXT       1070
#define IDC_BG_COLOUR_BUTTON            1071
#define IDC_SCALE_EDIT                  1072
#define IDC_BLOCK_EDIT                  1073
#define IDC_SCALE_R_EDIT                1073
#define IDC_SCALE_H_EDIT                1074
#define IDC_PEAK_CHECK                  1075
#define IDC_LEFT_TIME_COMBO             1076
#define IDC_RIGHT_TIME_COMBO            1077
#define IDC_LEFT_TIME_STATIC_TEXT       1078
#define IDC_RIGHT_TIME_STATIC_TEXT      1079
#define IDC_COLOUR_STATIC_TEXT          1080
#define IDC_COLOUR_STATIC               1081
#define IDC_COLOUR_BUTTON               1082
#define IDC_LINE1_STATIC                1084
#define IDC_LINE2_STATIC                1085
#define IDC_LINE3_STATIC                1086
#define IDC_SCALE_STATIC                1087
#define IDC_OFFSET_STATIC               1088
#define IDC_LEFT_STATIC                 1089
#define IDC_POST_SCALE_STATIC           1090
#define IDC_RIGHT_STATIC                1090
#define IDC_SCROLL_V_SPEED_STATIC       1091
#define IDC_SCROLL_H_DELAY_STATIC       1092
#define IDC_SCROLL_V_DELAY_STATIC       1093
#define IDC_FONT_ALIGN_H_STATIC         1094
#define IDC_CFG_STATIC                  1095
#define IDC_SCROLL_H_SPEED_EDIT         1096
#define IDC_SCROLL_H_DELAY_EDIT         1097
#define IDC_SCROLL_V_SPEED_EDIT         1098
#define IDC_SCROLL_V_DELAY_EDIT         1099
#define IDC_FONT_ALIGN_V_STATIC         1100
#define IDC_PROGRESS_HEIGHT_EDIT        1101
#define IDC_FONT_ALIGN_V_STATIC2        1102
#define IDC_FONT_ALIGN_H_COMBO          1104
#define IDC_SCROLL_H_GAP_EDIT           1105
#define IDC_SCROLL_V_GAP_EDIT           1106
#define IDC_TRACK_INFO_TABS             1107
#define IDC_SCROLL_V_GAP_STATIC         1108
#define IDC_STATIC_SIZER_2              1109
#define IDC_SPEC_MODE_STATIC            1110
#define IDC_SPEC_MODE_COMBO             1111
#define IDC_PRE_SCALE_STATIC            1112
#define IDC_EXPERT_MODE_STATIC          1113
#define IDC_OFFSET_EDIT                 1114
#define IDC_EXPERT_MODE_STATIC2         1114
#define IDC_GAP_CHECK                   1115
#define IDC_OFFSET_EDIT2                1115
#define IDC_OFFSET_R_EDIT               1115
#define IDC_OFFSET_H_EDIT               1116
#define IDC_POST_SCALE_EDIT             1117
#define IDC_PERM_SONG_INFO_CHECK        1118
#define IDC_COLOUR_1_BUTTON             1119
#define IDC_COLOUR_1_STATIC             1120
#define IDC_COLOUR_1_STATIC_TEXT        1121
#define IDC_FONT_ALIGN_STATIC           1122
#define IDC_BLOCK_STATIC                1123
#define IDC_TRACK_INFO_TIME_EDIT        1124
#define IDC_SCROLLING_STATIC            1125
#define IDC_SCALE_W_STATIC              1126
#define IDC_WIDTH_STATIC                1126
#define IDC_START_WITH_STATIC           1127
#define IDC_SCROLL_H_SPEED_STATIC       1128
#define IDC_SCALE_H_STATIC              1129
#define IDC_HEIGHT_STATIC               1129
#define IDC_COLOUR_LCD_STATIC           1130
#define IDC_BACKGROUND_IMG_STATIC       1131
#define IDC_BG_FILE_BUTTON              1132
#define IDC_FONT_ALIGN_H_STATIC2        1133
#define IDC_PROGRESS_HEIGHT_STATIC      1134
#define IDC_SCROLL_H_GAP_STATIC         1135
#define IDC_SCROLL_MODE_H_COMBO         1136
#define IDC_ALBUM_ART_TYPE_COMBO        1137
#define IDC_ALBUM_ART_TYPE_STATIC       1138
#define IDC_PRE_SCALE_EDIT              1139
#define IDC_SCALE_L_EDIT                1140
#define IDC_OFFSET_L_EDIT               1141
#define IDC_SCALE_W_EDIT                1142
#define IDC_OFFSET_W_EDIT               1143
#define IDC_TRACK_INFO_SIZER            1144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
